apiVersion: v1
kind: Service
metadata:
  name: laravel-project
  namespace: default
spec:
  selector:
    app: task-k8s
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
